version: "3.5"
services:
  dwh-e1:
    build:
      context: .
    container_name: dwh-e1
    ports:
      - "4000:4000"
  mysql:
    image: budougumi0617/mysql-sakila
    container_name: mysql-dwh-e1-app
    environment: 
      MYSQL_ROOT_PASSWORD: 'root'
      DB_NAME: 'sakila'
    ports:
      - "43306:3306"
